swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /users:
    get:
      operationId: people.read_all
      tags:
        - people
      summary: Read the entire list of people
      description: Read the list of people
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of people to get from people
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering people
          required: false
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: integer
                age:
                  type: integer
                sex:
                  type: string

    post:
      operationId: people.create
      tags:
        - people
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of person to create
              lname:
                type: string
                description: Last name of person to create
      responses:
        201:
          description: Successfully created person in list

  /users/{user_id}:
    get:
      operationId: people.read_one
      tags:
        - people
      summary: Read one person from the people list
      description: Read one person from the people list
      parameters:
        - name: user_id
          in: path
          description: userid of the person to get from the list
          type: integer
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: integer
                age:
                  type: integer
                sex:
                  type: string

    put:
      operationId: people.update
      tags:
        - people
      summary: Update a person in the people list
      description: Update a person in the people list
      parameters:
        - name: user_id
          in: path
          description: Last name of the person to update in the list
          type: string
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
      responses:
        200:
          description: Successfully updated person in people list

    delete:
      operationId: people.delete
      tags:
        - people
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: user_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a person from people list

  /rating/{user_id}:
    get:
      operationId: rating.ratings_user
      tags:
      - rating
      summary: Read all ratings of given person
      description: Read all ratings of given person
      parameters:
      - name: user_id
        in: path
        description: user_id of person whose ratings you want
        type: integer
        required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            type: array
            items:
              properties:
                item:
                  type: integer
                rating:
                  type: integer

  /rating/{user_id}/{item_id}:
    get:
      operationId: rating.rating_user_item
      tags:
      - rating
      summary: Read all ratings of given person
      description: Read all ratings of given person
      parameters:
      - name: user_id
        in: path
        description: user_id of person whose ratings you want
        type: integer
        required: True
      - name: item_id
        in: path
        description: item_id of item which ratings you want
        type: integer
        required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            type: array
            items:
              properties:
                item:
                  type: integer
                rating:
                  type: integer

  /recommendation/FunkSVD/{user_id}:
    get:
      operationId: recommendation.get_recommendations_Funk_SVD
      tags:
      - recommendation
      summary: give recommendations for the given user
      description: Giver recommendations for the given user
      parameters:
      - name: user_id
        in: path
        description: user_id of person for who you want recommendations
        type: integer
        required: True
      - name: nb_recommendations
        in: query
        type: integer
        description: Number of recommendations to get for the given user
        required: false
      responses:
        200:
          description: Successfully calculated recommendations
          schema:
            type: array
            items:
              properties:
                item:
                  type: integer
                score:
                  type: integer

  /recommendation/KNN/{user_id}:
    get:
      operationId: recommendation.get_recommendations_KNN
      tags:
      - recommendation
      summary: give recommendations for the given user
      description: Giver recommendations for the given user
      parameters:
      - name: user_id
        in: path
        description: user_id of person for who you want recommendations
        type: integer
        required: True
      - name: nb_recommendations
        in: query
        type: integer
        description: Number of recommendations to get for the given user
        required: false
      responses:
        200:
          description: Successfully calculated recommendations
          schema:
            type: array
            items:
              properties:
                item:
                  type: integer
                score:
                  type: integer

